# Generated by Django 5.2.17 on 2026-10-02 18:37

import django.core.validators
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(error_messages={'unique': 'Já existe um produto com este código.'}, help_text='Identificador único do produto. Exemplo: TEC-001.', max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._-]*$', 'Use letras, números, ponto, hífen ou sublinhado, sem espaços.')], verbose_name='Código / SKU')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do produto')),
                ('categoria', models.CharField(blank=True, help_text='Opcional. Exemplo: Periféricos.', max_length=100, verbose_name='Categoria')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('CX', 'Caixa')], default='UN', max_length=2, verbose_name='Unidade de contagem')),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Use vírgula para os centavos. Exemplo: 125,90.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de referência (R$)')),
                ('estoque_minimo', models.PositiveIntegerField(default=0, help_text='Quantidade inteira maior ou igual a zero.', verbose_name='Estoque mínimo')),
                ('saldo', models.PositiveIntegerField(default=0, editable=False, verbose_name='Saldo atual')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome', 'pk'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('codigo'), name='estoque_codigo_sem_diferenca_de_caixa', violation_error_message='Já existe um produto com este código.'), models.CheckConstraint(condition=models.Q(('preco__gte', 0)), name='estoque_preco_nao_negativo')],
            },
        ),
    ]
