# Generated by Django 5.2.17 on 2026-10-09 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_entradaestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(help_text='Informe uma quantidade inteira maior que zero.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade retirada')),
                ('observacao', models.CharField(blank=True, help_text='Opcional. Exemplo: Venda de mercadoria.', max_length=255, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Saída de estoque',
                'verbose_name_plural': 'Saídas de estoque',
                'ordering': ['-criado_em', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='estoque_saida_quantidade_positiva')],
            },
        ),
    ]
